/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controlador;

import Model.TipoEmpleado;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Alonso
 */
public class PersonalCE extends javax.swing.JDialog {

    /**
     * Creates new form EditarPersonal
     */
    public PersonalCE(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Mikhuna");
        this.setSize(550, 350);
        this.setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_codigoP = new javax.swing.JTextField();
        jtxt_nombreP = new javax.swing.JTextField();
        jcmb_tipoP = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("CODIGO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 60, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 120, 50, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("TIPO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 40, 15);

        jtxt_codigoP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxt_codigoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_codigoPActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_codigoP);
        jtxt_codigoP.setBounds(140, 50, 340, 30);

        jtxt_nombreP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxt_nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombrePActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_nombreP);
        jtxt_nombreP.setBounds(140, 110, 340, 30);

        jcmb_tipoP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcmb_tipoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_tipoPActionPerformed(evt);
            }
        });
        getContentPane().add(jcmb_tipoP);
        jcmb_tipoP.setBounds(140, 170, 110, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("CONFIRMAR");
        jButton1.setPreferredSize(new java.awt.Dimension(90, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 270, 100, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.setPreferredSize(new java.awt.Dimension(90, 20));
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 270, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_codigoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_codigoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_codigoPActionPerformed

    private void jtxt_nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombrePActionPerformed

    private void jcmb_tipoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_tipoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_tipoPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PersonalCE dialog = new PersonalCE(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<TipoEmpleado> jcmb_tipoP;
    private javax.swing.JTextField jtxt_codigoP;
    private javax.swing.JTextField jtxt_nombreP;
    // End of variables declaration//GEN-END:variables

    private void loadComboBox() {
        jcmb_tipoP.setModel(new DefaultComboBoxModel<>(TipoEmpleado.values()));
    }
}
