package Controlador;

import Model.TipoAlimento;
import javax.swing.DefaultComboBoxModel;

public class PlatosIndividuales extends javax.swing.JDialog {

    public PlatosIndividuales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Mikhuna");
        master
        this.setSize(800, 600);

        this.setSize(950, 550);
        master
        this.setResizable(false);
        setLocationRelativeTo(null);
        loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jcmb_tipoPI = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_listaAlimentos = new javax.swing.JTable();
        jbtn_atrasPI = new javax.swing.JButton();
        jbtn_crearnuevoPI = new javax.swing.JButton();
        jbtn_editarPI = new javax.swing.JButton();
        jbtn_eliminarPI = new javax.swing.JButton();
        jbtn_exportarPI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtn_buscarPI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 160, 235, 30);

        jcmb_tipoPI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jcmb_tipoPI);
        master
        jcmb_tipoPI.setBounds(540, 160, 130, 30);

        jcmb_tipoPI.setBounds(680, 120, 170, 30);
        master

        jtbl_listaAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "ALIMENTO", "PRECIO", "TIPO", "ULTIMA EDICION"
            }
        ));
        jScrollPane1.setViewportView(jtbl_listaAlimentos);

        getContentPane().add(jScrollPane1);
        master
        jScrollPane1.setBounds(50, 230, 700, 320);

        jScrollPane1.setBounds(50, 180, 850, 280);
        master

        jbtn_atrasPI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtn_atrasPI.setText("<<");
        jbtn_atrasPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_atrasPIActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_atrasPI);
        jbtn_atrasPI.setBounds(50, 40, 60, 40);

        jbtn_crearnuevoPI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtn_crearnuevoPI.setText("<html> <body> <div style= \"text-align: center; color: black;\"> <p>CREAR</p> <p>NUEVO</p> </div> </body> </html> ");
        jbtn_crearnuevoPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_crearnuevoPIActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_crearnuevoPI);
        jbtn_crearnuevoPI.setBounds(120, 40, 100, 40);

        jbtn_editarPI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtn_editarPI.setText("EDITAR");
        jbtn_editarPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_editarPIActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_editarPI);
        jbtn_editarPI.setBounds(230, 40, 80, 40);

        jbtn_eliminarPI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtn_eliminarPI.setText("ELIMINAR");
        getContentPane().add(jbtn_eliminarPI);
        jbtn_eliminarPI.setBounds(320, 40, 85, 40);

        jbtn_exportarPI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtn_exportarPI.setText("EXPORTAR");
        getContentPane().add(jbtn_exportarPI);
        jbtn_exportarPI.setBounds(420, 40, 93, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("LISTA DE ALIMENTOS");
        getContentPane().add(jLabel2);
        master
        jLabel2.setBounds(340, 110, 140, 17);

        jLabel2.setBounds(420, 80, 140, 17);
        master

        jbtn_buscarPI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtn_buscarPI.setText("BUSCAR");
        getContentPane().add(jbtn_buscarPI);
        jbtn_buscarPI.setBounds(320, 160, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_crearnuevoPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_crearnuevoPIActionPerformed

    }//GEN-LAST:event_jbtn_crearnuevoPIActionPerformed

    private void jbtn_editarPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_editarPIActionPerformed

    }//GEN-LAST:event_jbtn_editarPIActionPerformed

    private void jbtn_atrasPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_atrasPIActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtn_atrasPIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlatosIndividuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlatosIndividuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlatosIndividuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlatosIndividuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlatosIndividuales dialog = new PlatosIndividuales(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtn_atrasPI;
    private javax.swing.JButton jbtn_buscarPI;
    private javax.swing.JButton jbtn_crearnuevoPI;
    private javax.swing.JButton jbtn_editarPI;
    private javax.swing.JButton jbtn_eliminarPI;
    private javax.swing.JButton jbtn_exportarPI;
    private javax.swing.JComboBox<TipoAlimento> jcmb_tipoPI;
    private javax.swing.JTable jtbl_listaAlimentos;
    // End of variables declaration//GEN-END:variables

    private void loadComboBox() {
        jcmb_tipoPI.setModel(new DefaultComboBoxModel<>(TipoAlimento.values()));
    }
}